
all: calc tests

calc: main.o
	g++ -o calc main.o

tests: tests.o
	g++ -o tests tests.o

main.o: functions.h
	g++ -c main.cpp

tests.o: functions.h
	g++ -c tests.cpp

run:
	./calc $(arg)

test:
	tests 1 + 1 2
	tests 2 + 2 4
	tests 3 + 3 6
	tests 1 / 0 std::exception
	tests 1 + 3 / 4 + 5 - 6 + 7 7.75
	tests -1 -1
	tests -1 + -1 -2
	